# Generated by Django 5.2.4 on 2025-08-01 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        ('farms', '0006_block'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('FERT', 'Fertilisation'), ('IRR', 'Irrigation'), ('PLANT', 'Planting'), ('HARV', 'Harvesting'), ('PEST', 'PesticideApplication')], max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fertilizer_type', models.CharField(max_length=100)),
                ('npk_ratio', models.CharField(max_length=10)),
                ('application_method', models.CharField(max_length=50)),
                ('application_rate', models.FloatField()),
                ('block_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_block', to='farms.block')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_crop', to='crops.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_farm', to='farms.farm')),
                ('operator_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_operator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Harvesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('FERT', 'Fertilisation'), ('IRR', 'Irrigation'), ('PLANT', 'Planting'), ('HARV', 'Harvesting'), ('PEST', 'PesticideApplication')], max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('harvest_method', models.CharField(max_length=50)),
                ('yield_quantity', models.FloatField()),
                ('yield_quality', models.CharField(max_length=20)),
                ('harvest_notes', models.TextField(blank=True, null=True)),
                ('block_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_block', to='farms.block')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_crop', to='crops.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_farm', to='farms.farm')),
                ('operator_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_operator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('FERT', 'Fertilisation'), ('IRR', 'Irrigation'), ('PLANT', 'Planting'), ('HARV', 'Harvesting'), ('PEST', 'PesticideApplication')], max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('irrigation_method', models.CharField(max_length=50)),
                ('water_volume', models.FloatField()),
                ('duration', models.DurationField()),
                ('soil_moisture_pre', models.CharField(max_length=10)),
                ('block_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_block', to='farms.block')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_crop', to='crops.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_farm', to='farms.farm')),
                ('operator_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_operator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PesticideApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('FERT', 'Fertilisation'), ('IRR', 'Irrigation'), ('PLANT', 'Planting'), ('HARV', 'Harvesting'), ('PEST', 'PesticideApplication')], max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pesticide_name', models.CharField(max_length=100)),
                ('pesticide_type', models.CharField(max_length=100)),
                ('target_pest', models.CharField(max_length=50)),
                ('application_rate', models.FloatField()),
                ('withholding_period', models.FloatField()),
                ('block_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_block', to='farms.block')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_crop', to='crops.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_farm', to='farms.farm')),
                ('operator_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_operator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('FERT', 'Fertilisation'), ('IRR', 'Irrigation'), ('PLANT', 'Planting'), ('HARV', 'Harvesting'), ('PEST', 'PesticideApplication')], max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('seed_variety', models.CharField(max_length=100)),
                ('seed_source', models.CharField(max_length=100)),
                ('planting_method', models.CharField(choices=[('DIRECT', 'Direct-seeding'), ('TRANSPLANT', 'Transplanting')], max_length=10)),
                ('planting_density', models.FloatField()),
                ('row_spacing', models.FloatField()),
                ('block_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_block', to='farms.block')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_crop', to='crops.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_farm', to='farms.farm')),
                ('operator_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_operator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
