# Generated by Django 5.2.4 on 2025-07-28 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0006_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(max_length=75)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='farms.farm')),
            ],
        ),
    ]
