# Generated by Django 5.2.4 on 2025-07-28 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_operations', '0001_initial'),
        ('farms', '0006_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilisation',
            fields=[
                ('farmoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm_operations.farmoperation')),
                ('fertilizer_type', models.CharField(max_length=100)),
                ('npk_ratio', models.CharField(max_length=10)),
                ('application_method', models.CharField(max_length=50)),
                ('application_rate', models.FloatField()),
            ],
            bases=('farm_operations.farmoperation',),
        ),
        migrations.CreateModel(
            name='Harvesting',
            fields=[
                ('farmoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm_operations.farmoperation')),
                ('harvest_method', models.CharField(max_length=50)),
                ('yield_quantity', models.FloatField()),
                ('yield_quality', models.CharField(max_length=20)),
                ('harvest_notes', models.TextField(blank=True, null=True)),
            ],
            bases=('farm_operations.farmoperation',),
        ),
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('farmoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm_operations.farmoperation')),
                ('irrigation_method', models.CharField(max_length=50)),
                ('water_volume', models.FloatField()),
                ('duration', models.DurationField()),
                ('soil_moisture_pre', models.CharField(max_length=10)),
            ],
            bases=('farm_operations.farmoperation',),
        ),
        migrations.CreateModel(
            name='PesticideApplication',
            fields=[
                ('farmoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm_operations.farmoperation')),
                ('pesticide_name', models.CharField(max_length=100)),
                ('pesticide_type', models.CharField(max_length=100)),
                ('target_pest', models.CharField(max_length=50)),
                ('application_rate', models.FloatField()),
                ('withholding_period', models.FloatField()),
            ],
            bases=('farm_operations.farmoperation',),
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('farmoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='farm_operations.farmoperation')),
                ('seed_variety', models.CharField(max_length=100)),
                ('seed_source', models.CharField(max_length=100)),
                ('planting_method', models.CharField(max_length=50)),
                ('planting_density', models.FloatField()),
                ('row_spacing', models.FloatField()),
            ],
            bases=('farm_operations.farmoperation',),
        ),
        migrations.RemoveField(
            model_name='farmoperation',
            name='record_type',
        ),
        migrations.AddField(
            model_name='farmoperation',
            name='block_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='block', to='farms.block'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmoperation',
            name='crop',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmoperation',
            name='operation_type',
            field=models.CharField(choices=[('FERT', 'Fertilisation'), ('IRR', 'Irrigation'), ('PLANT', 'Planting'), ('HARV', 'Harvesting'), ('PEST', 'PesticideApplication')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmoperation',
            name='operator_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmoperation',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm', to='farms.farm'),
        ),
    ]
