# Generated by Django 5.2.4 on 2025-07-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='title',
            new_name='name',
        ),
    ]
