# Generated by Django 5.2.4 on 2025-07-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_rename_title_farm_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='body',
            new_name='size_hectares',
        ),
        migrations.AddField(
            model_name='farm',
            name='farm_lat',
            field=models.CharField(default=38.877587, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='farm_long',
            field=models.CharField(default=-9.412062, max_length=20),
            preserve_default=False,
        ),
    ]
