# Generated by Django 5.2.4 on 2025-07-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_rename_body_farm_size_hectares_farm_farm_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='size_hectares',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='farm',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
