# Generated by Django 5.2.4 on 2025-07-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_alter_farm_size_hectares_alter_farm_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
